elasticsearch:
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 4000m
        memory: 4000Mi
  data:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 4000m
        memory: 4000Mi
  client:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 4000m
        memory: 4000Mi

elasticsearch-curator:
  enabled: true
  configMaps:
    config_yml: |-
      ---
      client:
        hosts:
          - efk-elasticsearch-client.logging
        port: 9200

logstash:
  enabled: false

fluent-bit:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 2000Mi
      memory: 1000Mi
  backend:
    type: es
    es:
      host: efk-elasticsearch-client.logging

kibana:
  enabled: true
  env:
    ELASTICSEARCH_HOSTS: http://efk-elasticsearch-client.logging:9200
