{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "orca.fullname" . }}
  labels:
{{ include "orca.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # TODO: limit to only required resources/verbs
subjects:
  - kind: ServiceAccount
    name: {{ template "orca.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
