kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "orca.fullname" . }}
  labels:
{{ include "orca.labels" . | indent 4 }}
data:
  orca.yaml: |-
{{ (.Files.Glob "config/alerts-mapping.yaml").AsConfig | indent 2 }}
