image:
  tag: 0.1.39

elasticsearch:
  host: "elasticsearch-client.logging"
  port: 9200

runIntervalMins: 1
alertRetryLimitMins: 1
realertIntervalMins: 1
bufferTimeMins: 15
writebackIndex: elastalert_status

rules:
  webhook-test: |-
    ---
    name: Application error
    type: frequency
    index: kubernetes_cluster-*
    num_events: 3
    timeframe:
      minutes: 1
    filter:
    - term:
        stream: "stderr"
    aggregation:
      minutes: 1
    aggregation_key: "kubernetes.pod_name"
    alert:
    - "post"
    http_post_url: "http://orca.rca:5000/v1/ingestor/elastalert"
    http_post_static_payload:
      name: "Application error"
      status: active
      severity: warning
      message: "Application populated entries to error stream"

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1000Mi
