prometheus:
  mappings:
    - name: KubePodNotReady
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubePodCrashLooping
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubeContainerWaiting
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
    - name: KubeDeploymentReplicasMismatch
      source_mapping:
        kind: deployment
        properties:
          name: deployment
          namespace: namespace
    - name: KubeStatefulSetReplicasMismatch
      source_mapping:
        kind: stateful_set
        properties:
          name: statefulset
          namespace: namespace
    - name: CPUThrottlingHigh
      source_mapping:
        kind: pod
        properties:
          name: pod
          namespace: namespace
falco:
  blacklist_values:
    - '<NA>'
  mappings:
    - name: "Launch Sensitive Mount Container"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
    - name: "Launch Privileged Container"
      source_mapping:
        kind: pod
        properties:
          name: k8s.pod.name
          namespace: k8s.ns.name
    - name: "Create Sensitive Mount Pod"
      source_mapping:
        kind: pod
        properties:
          name: ka.resp.name
          namespace: ka.target.namespace
    - name: "Create Privileged Pod"
      source_mapping:
        kind: pod
        properties:
          name: ka.resp.name
          namespace: ka.target.namespace

